export function secondsToHumanTime(seconds) {
    seconds = Number(seconds);
    var d = Math.floor(seconds / (3600*24));
    var h = Math.floor(seconds % (3600*24) / 3600);
    var m = Math.floor(seconds % 3600 / 60);
    var s = Math.floor(seconds % 60);
    
    var dDisplay = d > 0 ? d + (d == 1 ? "d " : "d ") : "";
    var hDisplay = h > 0 ? h + (h == 1 ? "h " : "h ") : "";
    var mDisplay = m > 0 ? m + (m == 1 ? "m " : "m ") : "";
    var sDisplay = s > 0 ? s + (s == 1 ? "s" : "s") : "";
    
    return dDisplay + hDisplay + mDisplay + sDisplay;
}

export function getLastSessionGames(data){
    return data.slice(0, 5);
    const filteredArray = [];

    if(!data.length) return filteredArray

    for (let i = 0; i < data.length; i++) {
        if (i === 0 || (data[i].gameEndTimestamp - data[i - 1].gameEndTimestamp) < 3600000) {
            // If it's the first element or the current date is more than 1 hour older
            filteredArray.push(data[i]);
        } else {
            // Break out of the loop as soon as the condition is not met
            break;
        }
    }

    console.log(filteredArray.length)

    return filteredArray
}

let o = {
    "allInPings": 0,
    "assistMePings": 0,
    "assists": 7,
    "baronKills": 0,
    "basicPings": 0,
    "bountyLevel": 0,
    "challenges": {
        "12AssistStreakCount": 0,
        "abilityUses": 287,
        "acesBefore15Minutes": 0,
        "alliedJungleMonsterKills": 2,
        "baronBuffGoldAdvantageOverThreshold": 1,
        "baronTakedowns": 1,
        "blastConeOppositeOpponentCount": 0,
        "bountyGold": 300,
        "buffsStolen": 0,
        "completeSupportQuestInTime": 0,
        "controlWardsPlaced": 1,
        "damagePerMinute": 1002.8494091308058,
        "damageTakenOnTeamPercentage": 0.2836947410577812,
        "dancedWithRiftHerald": 0,
        "deathsByEnemyChamps": 11,
        "dodgeSkillShotsSmallWindow": 3,
        "doubleAces": 0,
        "dragonTakedowns": 1,
        "earliestBaron": 1618.9400798,
        "earliestDragonTakedown": 2099.0235638999998,
        "earliestElderDragon": 2099.0235638999998,
        "earlyLaningPhaseGoldExpAdvantage": 0,
        "effectiveHealAndShielding": 0,
        "elderDragonKillsWithOpposingSoul": 0,
        "elderDragonMultikills": 0,
        "enemyChampionImmobilizations": 17,
        "enemyJungleMonsterKills": 2,
        "epicMonsterKillsNearEnemyJungler": 0,
        "epicMonsterKillsWithin30SecondsOfSpawn": 0,
        "epicMonsterSteals": 0,
        "epicMonsterStolenWithoutSmite": 0,
        "firstTurretKilled": 1,
        "firstTurretKilledTime": 867.6895006,
        "flawlessAces": 0,
        "fullTeamTakedown": 0,
        "gameLength": 2386.7335166,
        "getTakedownsInAllLanesEarlyJungleAsLaner": 0,
        "goldPerMinute": 404.9828380749401,
        "hadOpenNexus": 0,
        "immobilizeAndKillWithAlly": 5,
        "initialBuffCount": 0,
        "initialCrabCount": 0,
        "jungleCsBefore10Minutes": 0,
        "junglerTakedownsNearDamagedEpicMonster": 0,
        "kTurretsDestroyedBeforePlatesFall": 0,
        "kda": 1.5454545454545454,
        "killAfterHiddenWithAlly": 3,
        "killParticipation": 0.2833333333333333,
        "killedChampTookFullTeamDamageSurvived": 0,
        "killingSprees": 2,
        "killsNearEnemyTurret": 2,
        "killsOnOtherLanesEarlyJungleAsLaner": 0,
        "killsOnRecentlyHealedByAramPack": 0,
        "killsUnderOwnTurret": 0,
        "killsWithHelpFromEpicMonster": 0,
        "knockEnemyIntoTeamAndKill": 7,
        "landSkillShotsEarlyGame": 0,
        "laneMinionsFirst10Minutes": 59,
        "laningPhaseGoldExpAdvantage": 0,
        "legendaryCount": 0,
        "legendaryItemUsed": [
            6653,
            4633,
            6665,
            3116
        ],
        "lostAnInhibitor": 1,
        "maxCsAdvantageOnLaneOpponent": 12,
        "maxKillDeficit": 2,
        "maxLevelLeadLaneOpponent": 1,
        "mejaisFullStackInTime": 0,
        "moreEnemyJungleThanOpponent": 0,
        "multiKillOneSpell": 1,
        "multiTurretRiftHeraldCount": 0,
        "multikills": 2,
        "multikillsAfterAggressiveFlash": 0,
        "outerTurretExecutesBefore10Minutes": 0,
        "outnumberedKills": 4,
        "outnumberedNexusKill": 0,
        "perfectDragonSoulsTaken": 1,
        "perfectGame": 0,
        "pickKillWithAlly": 11,
        "playedChampSelectPosition": 1,
        "poroExplosions": 0,
        "quickCleanse": 0,
        "quickFirstTurret": 0,
        "quickSoloKills": 0,
        "riftHeraldTakedowns": 0,
        "saveAllyFromDeath": 0,
        "scuttleCrabKills": 0,
        "skillshotsDodged": 40,
        "skillshotsHit": 0,
        "snowballsHit": 0,
        "soloBaronKills": 0,
        "soloKills": 5,
        "stealthWardsPlaced": 14,
        "survivedSingleDigitHpCount": 0,
        "survivedThreeImmobilizesInFight": 8,
        "takedownOnFirstTurret": 0,
        "takedowns": 17,
        "takedownsAfterGainingLevelAdvantage": 0,
        "takedownsBeforeJungleMinionSpawn": 0,
        "takedownsFirstXMinutes": 1,
        "takedownsInAlcove": 1,
        "takedownsInEnemyFountain": 0,
        "teamBaronKills": 2,
        "teamDamagePercentage": 0.23092416326516998,
        "teamElderDragonKills": 1,
        "teamRiftHeraldKills": 0,
        "tookLargeDamageSurvived": 1,
        "turretPlatesTaken": 1,
        "turretTakedowns": 4,
        "turretsTakenWithRiftHerald": 0,
        "twentyMinionsIn3SecondsCount": 0,
        "twoWardsOneSweeperCount": 0,
        "unseenRecalls": 0,
        "visionScoreAdvantageLaneOpponent": 0.2995271682739258,
        "visionScorePerMinute": 0.6927410853368073,
        "wardTakedowns": 1,
        "wardTakedownsBefore20M": 1,
        "wardsGuarded": 0
    },
    "champExperience": 22506,
    "champLevel": 18,
    "championId": 82,
    "championName": "Mordekaiser",
    "championTransform": 0,
    "commandPings": 2,
    "consumablesPurchased": 6,
    "damageDealtToBuildings": 5970,
    "damageDealtToObjectives": 14865,
    "damageDealtToTurrets": 5970,
    "damageSelfMitigated": 90761,
    "dangerPings": 0,
    "deaths": 11,
    "detectorWardsPlaced": 1,
    "doubleKills": 2,
    "dragonKills": 0,
    "eligibleForProgression": true,
    "enemyMissingPings": 4,
    "enemyVisionPings": 2,
    "firstBloodAssist": false,
    "firstBloodKill": false,
    "firstTowerAssist": false,
    "firstTowerKill": false,
    "gameEndedInEarlySurrender": false,
    "gameEndedInSurrender": false,
    "getBackPings": 0,
    "goldEarned": 16109,
    "goldSpent": 14875,
    "holdPings": 0,
    "individualPosition": "TOP",
    "inhibitorKills": 0,
    "inhibitorTakedowns": 1,
    "inhibitorsLost": 1,
    "item0": 3116,
    "item1": 6653,
    "item2": 3047,
    "item3": 4633,
    "item4": 6665,
    "item5": 3211,
    "item6": 3340,
    "itemsPurchased": 28,
    "killingSprees": 2,
    "kills": 10,
    "lane": "MIDDLE",
    "largestCriticalStrike": 0,
    "largestKillingSpree": 4,
    "largestMultiKill": 2,
    "longestTimeSpentLiving": 327,
    "magicDamageDealt": 167114,
    "magicDamageDealtToChampions": 31725,
    "magicDamageTaken": 13178,
    "missions": {
        "playerScore0": 0,
        "playerScore1": 0,
        "playerScore10": 0,
        "playerScore11": 0,
        "playerScore2": 0,
        "playerScore3": 0,
        "playerScore4": 0,
        "playerScore5": 0,
        "playerScore6": 0,
        "playerScore7": 0,
        "playerScore8": 0,
        "playerScore9": 0
    },
    "needVisionPings": 0,
    "neutralMinionsKilled": 3,
    "nexusKills": 0,
    "nexusLost": 0,
    "nexusTakedowns": 1,
    "objectivesStolen": 0,
    "objectivesStolenAssists": 0,
    "onMyWayPings": 3,
    "participantId": 1,
    "pentaKills": 0,
    "perks": {
        "statPerks": {
            "defense": 5002,
            "flex": 5008,
            "offense": 5005
        },
        "styles": [
            {
                "description": "primaryStyle",
                "selections": [
                    {
                        "perk": 8010,
                        "var1": 787,
                        "var2": 0,
                        "var3": 0
                    },
                    {
                        "perk": 9111,
                        "var1": 1688,
                        "var2": 340,
                        "var3": 0
                    },
                    {
                        "perk": 9105,
                        "var1": 21,
                        "var2": 50,
                        "var3": 0
                    },
                    {
                        "perk": 8299,
                        "var1": 1567,
                        "var2": 0,
                        "var3": 0
                    }
                ],
                "style": 8000
            },
            {
                "description": "subStyle",
                "selections": [
                    {
                        "perk": 8453,
                        "var1": 1416,
                        "var2": 1675,
                        "var3": 0
                    },
                    {
                        "perk": 8429,
                        "var1": 69,
                        "var2": 15,
                        "var3": 12
                    }
                ],
                "style": 8400
            }
        ]
    },
    "physicalDamageDealt": 24541,
    "physicalDamageDealtToChampions": 3507,
    "physicalDamageTaken": 33786,
    "placement": 0,
    "playerAugment1": 0,
    "playerAugment2": 0,
    "playerAugment3": 0,
    "playerAugment4": 0,
    "playerScore0": 0,
    "playerScore1": 0,
    "playerScore10": 0,
    "playerScore11": 0,
    "playerScore2": 0,
    "playerScore3": 0,
    "playerScore4": 0,
    "playerScore5": 0,
    "playerScore6": 0,
    "playerScore7": 0,
    "playerScore8": 0,
    "playerScore9": 0,
    "playerSubteamId": 0,
    "profileIcon": 3797,
    "pushPings": 0,
    "puuid": "knXyAT18wJ_dgsj2kSt3fe9rfw5UWYtfh8EgFbwZjG4Ug_Gz79R6E9jMglF2zcTABSTOu2JFqEKbRA",
    "quadraKills": 0,
    "riotIdGameName": "Gunsen BMX",
    "riotIdTagline": "EUW",
    "role": "SUPPORT",
    "sightWardsBoughtInGame": 0,
    "spell1Casts": 161,
    "spell2Casts": 51,
    "spell3Casts": 61,
    "spell4Casts": 14,
    "subteamPlacement": 0,
    "summoner1Casts": 5,
    "summoner1Id": 12,
    "summoner2Casts": 6,
    "summoner2Id": 4,
    "summonerId": "xw6frLdpuyz3_An0ks58vmxA20NxYIvKWSzF5qM_JK85VSBwSzkb4aX4og",
    "summonerLevel": 242,
    "summonerName": "Gunsen BMX",
    "teamEarlySurrendered": false,
    "teamId": 100,
    "teamPosition": "TOP",
    "timeCCingOthers": 8,
    "timePlayed": 2386,
    "totalAllyJungleMinionsKilled": 3,
    "totalDamageDealt": 199776,
    "totalDamageDealtToChampions": 39892,
    "totalDamageShieldedOnTeammates": 0,
    "totalDamageTaken": 50353,
    "totalEnemyJungleMinionsKilled": 0,
    "totalHeal": 15212,
    "totalHealsOnTeammates": 0,
    "totalMinionsKilled": 197,
    "totalTimeCCDealt": 116,
    "totalTimeSpentDead": 446,
    "totalUnitsHealed": 1,
    "tripleKills": 0,
    "trueDamageDealt": 8120,
    "trueDamageDealtToChampions": 4659,
    "trueDamageTaken": 3389,
    "turretKills": 2,
    "turretTakedowns": 4,
    "turretsLost": 8,
    "unrealKills": 0,
    "visionClearedPings": 0,
    "visionScore": 27,
    "visionWardsBoughtInGame": 1,
    "wardsKilled": 1,
    "wardsPlaced": 15,
    "win": true
}